addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("io.spray"          % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.typesafe.play" % "sbt-twirl"    % "1.6.0-M6")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.2")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "2.0.1")
