// scala code override def requires: Plugins = net.scalax.simple.nat.sbt.ProjectKeys

// start setting
{
    import net.scalax.simple.nat.sbt.ProjectKeys.autoImport._
    baseFilesToCross := {
      val tryValue = baseFilesToCross.?.value
      val newFile  = baseDirectory.value / ".." / "shared"
      newFile +: tryValue.toList.flatten
    }
}
// end setting

// scala code override lazy val projectSettings: Seq[Setting[_]] = preSettings
